"""Normalized Phase-4 semantic storage substrate."""

from .model import (
    AdmissionDecision,
    AdmissionLifecycleStatus,
    AssertionStatus,
    AssignmentStatus,
    CapabilityInstance,
    ClaimHistoryAction,
    ClaimHistoryRecord,
    ClaimRecord,
    ConditionTruth,
    DefaultRuleRecord,
    DependencyEdge,
    EpistemicAdmissionRecord,
    EvidenceRecord,
    GraphPatch,
    IdentityFacetRecord,
    KnowledgeRecord,
    KnowledgeStatus,
    MaterializedViewRecord,
    PatchCommitResult,
    PatchCommitStatus,
    PatchOperation,
    PatchOperationKind,
    RecordDependency,
    RecordKind,
    ReferentTypeAssertion,
    SourceAssessmentRecord,
    StateAssignment,
    StoreSnapshot,
    StoredRecord,
)

_LAZY_EXPORTS = {
    "RecordDecodeError": ".codec",
    "decode_record": ".codec",
    "encode_record": ".codec",
    "record_context": ".codec",
    "record_fingerprints": ".codec",
    "record_lifecycle": ".codec",
    "record_permission": ".codec",
    "record_ref": ".codec",
    "record_revision": ".codec",
    "CapabilityDependencyRecord": "..transitions.model",
    "TransitionContractRecord": "..transitions.model",
    "TransitionProofRecord": "..transitions.model",
    "RepositorySet": ".repositories",
    "interval_contains": ".repositories",
    "ReadOnlyBootError": ".store",
    "SemanticStore": ".store",
    "StoreConflictError": ".store",
    "StoreError": ".store",
    "CommitValidationError": ".validation",
    "CommitValidator": ".validation",
    "ValidationError": ".validation",
}


def __getattr__(name: str):
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(name)
    from importlib import import_module

    module = import_module(module_name, __package__)
    value = getattr(module, name)
    globals()[name] = value
    return value

__all__ = [
    "AdmissionDecision",
    "AdmissionLifecycleStatus",
    "AssertionStatus",
    "AssignmentStatus",
    "CapabilityInstance",
    "CapabilityDependencyRecord",
    "ClaimHistoryAction",
    "ClaimHistoryRecord",
    "ClaimRecord",
    "CommitValidationError",
    "CommitValidator",
    "ConditionTruth",
    "DefaultRuleRecord",
    "DependencyEdge",
    "EpistemicAdmissionRecord",
    "EvidenceRecord",
    "GraphPatch",
    "IdentityFacetRecord",
    "KnowledgeRecord",
    "KnowledgeStatus",
    "MaterializedViewRecord",
    "PatchCommitResult",
    "PatchCommitStatus",
    "PatchOperation",
    "PatchOperationKind",
    "ReadOnlyBootError",
    "RecordDecodeError",
    "RecordDependency",
    "RecordKind",
    "ReferentTypeAssertion",
    "RepositorySet",
    "SemanticStore",
    "SourceAssessmentRecord",
    "StateAssignment",
    "TransitionContractRecord",
    "TransitionProofRecord",
    "StoreConflictError",
    "StoreError",
    "StoreSnapshot",
    "StoredRecord",
    "ValidationError",
    "decode_record",
    "encode_record",
    "interval_contains",
    "record_context",
    "record_fingerprints",
    "record_lifecycle",
    "record_permission",
    "record_ref",
    "record_revision",
]
