"""Normalized Phase-4 semantic storage substrate."""

from .codec import (
    RecordDecodeError,
    decode_record,
    encode_record,
    record_context,
    record_fingerprints,
    record_lifecycle,
    record_permission,
    record_ref,
    record_revision,
)
from .model import (
    AssertionStatus,
    AssignmentStatus,
    CapabilityInstance,
    ClaimRecord,
    ConditionTruth,
    DefaultRuleRecord,
    DependencyEdge,
    EvidenceRecord,
    GraphPatch,
    IdentityFacetRecord,
    KnowledgeRecord,
    KnowledgeStatus,
    MaterializedViewRecord,
    PatchCommitResult,
    PatchCommitStatus,
    PatchOperation,
    PatchOperationKind,
    RecordDependency,
    RecordKind,
    ReferentTypeAssertion,
    StateAssignment,
    StoreSnapshot,
    StoredRecord,
)
from .repositories import RepositorySet, interval_contains
from .store import (
    ReadOnlyBootError,
    SemanticStore,
    StoreConflictError,
    StoreError,
)
from .validation import CommitValidationError, CommitValidator, ValidationError

__all__ = [
    "AssertionStatus",
    "AssignmentStatus",
    "CapabilityInstance",
    "ClaimRecord",
    "CommitValidationError",
    "CommitValidator",
    "ConditionTruth",
    "DefaultRuleRecord",
    "DependencyEdge",
    "EvidenceRecord",
    "GraphPatch",
    "IdentityFacetRecord",
    "KnowledgeRecord",
    "KnowledgeStatus",
    "MaterializedViewRecord",
    "PatchCommitResult",
    "PatchCommitStatus",
    "PatchOperation",
    "PatchOperationKind",
    "ReadOnlyBootError",
    "RecordDecodeError",
    "RecordDependency",
    "RecordKind",
    "ReferentTypeAssertion",
    "RepositorySet",
    "SemanticStore",
    "StateAssignment",
    "StoreConflictError",
    "StoreError",
    "StoreSnapshot",
    "StoredRecord",
    "ValidationError",
    "decode_record",
    "encode_record",
    "interval_contains",
    "record_context",
    "record_fingerprints",
    "record_lifecycle",
    "record_permission",
    "record_ref",
    "record_revision",
]
