"""Deterministic codecs for Phase-17 realization records."""
from __future__ import annotations
from typing import Any,Mapping
from ..learning.codec import _pin
from ..schema.model import SchemaLifecycleStatus,UseDecision,UseOperation,canonical_data
from .model import *

def realization_record_to_document(record:Any)->dict[str,Any]: return dict(canonical_data(record))
def realization_request_from_document(v):
 d=dict(v); return RealizationRequestRecord(str(d['request_ref']),_pin(dict(d['response_uol_pin'])),str(d['language_tag']),d.get('script'),d.get('locale_ref'),tuple(map(str,d.get('audience_refs',()))),tuple(map(str,d.get('register_refs',()))),tuple(_pin(dict(x)) for x in d.get('language_pack_pins',())),str(d['budget_ref']),str(d['permission_ref']),str(d.get('sensitivity','normal')),int(d.get('revision',1)),dict(d.get('metadata',{})))
def argument_frame_from_document(v):
 d=dict(v); return ArgumentFrameRecord(frame_ref=str(d['frame_ref']),pack_ref=str(d['pack_ref']),pack_revision=int(d['pack_revision']),predicate_schema_classes=tuple(map(str,d.get('predicate_schema_classes',()))),required_port_refs=tuple(map(str,d.get('required_port_refs',()))),optional_port_refs=tuple(map(str,d.get('optional_port_refs',()))),slot_order=tuple(map(str,d.get('slot_order',()))),port_to_slot=tuple((str(x[0]),str(x[1])) for x in d.get('port_to_slot',())),feature_constraints=tuple((str(x[0]),str(x[1])) for x in d.get('feature_constraints',())),discourse_act_refs=tuple(map(str,d.get('discourse_act_refs',()))),lifecycle_status=SchemaLifecycleStatus(str(d.get('lifecycle_status','candidate'))),use_operation=UseOperation(str(d.get('use_operation','realize'))),use_decision=UseDecision(str(d.get('use_decision','deny'))),permission_ref=str(d.get('permission_ref','public')),revision=int(d.get('revision',1)),supersedes_revision=None if d.get('supersedes_revision') is None else int(d['supersedes_revision']),metadata=dict(d.get('metadata',{})))
def morphology_rule_from_document(v):
 d=dict(v); return MorphologyRuleRecord(str(d['rule_ref']),str(d['pack_ref']),int(d['pack_revision']),str(d['lexical_category']),tuple((str(x[0]),str(x[1])) for x in d.get('required_features',())),MorphologyOperation(str(d['operation'])),str(d.get('operand','')),int(d.get('priority',0)),SchemaLifecycleStatus(str(d.get('lifecycle_status','candidate'))),UseOperation(str(d.get('use_operation','realize'))),UseDecision(str(d.get('use_decision','deny'))),str(d.get('permission_ref','public')),int(d.get('revision',1)),None if d.get('supersedes_revision') is None else int(d['supersedes_revision']),dict(d.get('metadata',{})))
def linearization_rule_from_document(v):
 d=dict(v); return LinearizationRuleRecord(str(d['rule_ref']),str(d['pack_ref']),int(d['pack_revision']),str(d['construction_ref']),tuple((str(x[0]),str(x[1])) for x in d.get('precedence_pairs',())),str(d.get('separator',' ')),tuple(map(str,d.get('prefix_tokens',()))),tuple(map(str,d.get('suffix_tokens',()))),SchemaLifecycleStatus(str(d.get('lifecycle_status','candidate'))),UseOperation(str(d.get('use_operation','realize'))),UseDecision(str(d.get('use_decision','deny'))),str(d.get('permission_ref','public')),int(d.get('revision',1)),None if d.get('supersedes_revision') is None else int(d['supersedes_revision']),dict(d.get('metadata',{})))
def deep_clause_plan_from_document(v):
 d=dict(v); return DeepClausePlanRecord(str(d['clause_ref']),_pin(dict(d['request_pin'])),str(d['response_application_ref']),str(d['predicate_schema_ref']),int(d['predicate_schema_revision']),tuple((str(x[0]),tuple((str(y[0]),str(y[1])) for y in x[1])) for x in d.get('argument_refs',())),d.get('discourse_act_ref'),tuple((str(x[0]),str(x[1])) for x in d.get('feature_values',())),tuple(map(str,d.get('scope_refs',()))),tuple(map(str,d.get('coordination_refs',()))),tuple((str(x[0]),str(x[1])) for x in d.get('information_structure',())),_pin(dict(d['frame_pin'])),int(d.get('revision',1)))
def reference_plan_from_document(v):
 d=dict(v); return ReferencePlanRecord(str(d['reference_ref']),_pin(dict(d['request_pin'])),_pin(dict(d['referent_pin'])),tuple(_pin(dict(x)) for x in d.get('competitor_pins',())),tuple(_pin(dict(x)) for x in d.get('allowed_identity_facet_pins',())),str(d['strategy_ref']),_pin(dict(d['language_rule_pin'])),tuple((str(x[0]),str(x[1])) for x in d.get('feature_values',())),int(d.get('revision',1)))
def surface_candidate_from_document(v):
 d=dict(v); return SurfaceCandidateRecord(candidate_ref=str(d['candidate_ref']),request_pin=_pin(dict(d['request_pin'])),clause_pins=tuple(_pin(dict(x)) for x in d.get('clause_pins',())),frame_pins=tuple(_pin(dict(x)) for x in d.get('frame_pins',())),lexical_pins=tuple(_pin(dict(x)) for x in d.get('lexical_pins',())),morphology_pins=tuple(_pin(dict(x)) for x in d.get('morphology_pins',())),reference_pins=tuple(_pin(dict(x)) for x in d.get('reference_pins',())),linearization_pins=tuple(_pin(dict(x)) for x in d.get('linearization_pins',())),tokens=tuple(map(str,d.get('tokens',()))),surface=str(d['surface']),generation_score=float(d['generation_score']),permission_ref=str(d['permission_ref']),snapshot_revision=int(d['snapshot_revision']),snapshot_fingerprint=str(d['snapshot_fingerprint']),revision=int(d.get('revision',1)),metadata=dict(d.get('metadata',{})))
def semantic_roundtrip_from_document(v):
 d=dict(v); return SemanticRoundTripRecord(str(d['roundtrip_ref']),_pin(dict(d['request_pin'])),_pin(dict(d['surface_candidate_pin'])),str(d['analyzer_ref']),str(d['analyzer_revision']),str(d['recovered_graph_fingerprint']),str(d['expected_graph_fingerprint']),RoundTripDecision(str(d['decision'])),tuple(map(str,d.get('additions',()))),tuple(map(str,d.get('losses',()))),tuple(map(str,d.get('drift_refs',()))),tuple(map(str,d.get('proof_refs',()))),int(d.get('revision',1)))
